### ISSUE TITLE
Fix javascript test coverage

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1048]
The current javascript test coverage output shows coverage for reprocessed / compiled javascript rather than the source code. Now that we have no more coffeescript / .cjsx compilations steps to worry about, we should be able to get more useful coverage data.

**Comment by mattfordham** [comment]
After kicking lots of tired and getting hands dirty, I ended up with a relatively subtle change. 

[This commit](https://github.com/WikiEducationFoundation/WikiEduDashboard/commit/63794255f1a5f54a75f606857a58a48a1e4a41f2) changes the JS coverage tool to [nyc](https://github.com/istanbuljs/nyc). This still uses [Istanbul](https://istanbul.js.org/) behind the scenes and appears to be much more maintained than gulp-jsx-coverage and its depenencies (at least the depencencies that enable the non-transpiled thing). 

I have updated the `npm test` command and the `.jscoverage` script. The gulp task is still in the repo, but we can delete after this is tested out. I'll leave this issue open for the sake of doing so.

**Comment by ragesoss** [comment]
@mattfordham the coverage output looks great … sadly, much lower than before, but more realistic. The build doesn't work, though. I get an error on loading any React page:

```
TypeError: n(...).default is not a function
```

(Also caused most of the feature tests to fail on travis.)

**Comment by mattfordham** [comment]
I hadn't considered how the change might affect the build yet... wanted to get your thoughts on the basic implementation first. 

That said, I'm a little confused as to why/how the coverage command would be messing with the build. It shouldn't have any output other than the coverage files. The JS used for the Ruby tests and deployment is compiled separately, right?

**Comment by mattfordham** [comment]
I must have screwed something else up, as I get that error locally when attempting to run. Will investigate tomorrow :)

**Comment by mattfordham** [comment]
@ragesoss Just a little tweak to the _.babelrc_ to get this working https://github.com/WikiEducationFoundation/WikiEduDashboard/commit/0f661fc1a94dd2c9c4411d6c98232086de79a0f3

Since the output is the same format and going to the same location, I am assuming CodeClimate will remain happy.
